symbol: SBIN
timeframe: 5m
capital: 60000
leverage: 5
ema_fast: 50
ema_medium: 100
ema_slow: 200
entry_distance_percent: 0.15
risk_reward: 3.00
square_off: "15:15"
entry_start: "09:20"
entry_end: "12:00"
sl_buffer_ticks: 2
trailing_step_rr: 0.5
trend_confirmation_bars: 10
enable_setup_a: true
enable_setup_b: false
enable_trailing_sl: false
start_date: "2023-07-07"
end_date: "2026-07-06"
