symbols: [
    "TMPV",
    "BAJFINANCE",
    "SBIN",
    "HINDUNILVR",
    "M&M",
    "HDFCBANK",
    "SUNPHARMA",
    "ICICIBANK",
    "ADANIPORTS",
    "APOLLOHOSP",
    "TATASTEEL",
    "MAXHEALTH",
    "HCLTECH",
    "MARUTI",
    "INDIGO",
    "POWERGRID"
  ] # Can be "ALL", a single symbol (e.g., "SBIN"), or a list (e.g., ["SBIN", "RELIANCE"])
timeframe: 5m
capital: 60000
leverage: 5
opening_range_mins: 15
volume_filter_multiplier: 2.0
volume_sma_len: 10
take_profit_pct: 1.50
stop_loss_pct: 1.00
square_off: "15:15"
entry_start: "09:30"
entry_end: "10:00"
enable_trailing_sl: false
trailing_trigger_rr: 2.0
trailing_step_rr: 0.5
output_dir: "market_data/orb"
start_date: "2023-07-07"
end_date: "2026-07-06"
