enable_live_stocks: true
symbols: [
    "ITI",
    "J&KBANK",
    "JAINREC",
    "JBCHEPHARM",
    "JBMA",
    "JINDALSAW",
    "JINDALSTEL",
    "JIOFIN",
    "JKCEMENT",
    "JKTYRE",
    "JMFINANCIL",
    "JPPOWER",
    "JSL",
    "JSWCEMENT",
    "JSWDULUX",
    "JSWENERGY",
    "JSWINFRA",
    "JSWSTEEL",
    "JUBLFOOD",
    "JUBLINGREA",
    "JUBLPHARMA",
    "JWL",
    "JYOTICNC",
    "KAJARIACER",
    "KALYANKJIL",
    "KARURVYSYA",
    "KAYNES",
    "KEC",
    "KEI",
    "KFINTECH",
    "KIMS",
    "KIRLOSENG",
    "KOTAKBANK",
    "KPIL",
    "KPITTECH",
    "KPRMILL",
    "LALPATHLAB",
    "LATENTVIEW",
    "LAURUSLABS",
    "LEMONTREE",
    "LENSKART",
    "LGEINDIA",
    "LICHSGFIN",
    "LICI",
    "LINDEINDIA",
    "LLOYDSME",
    "LODHA",
    "LT",
    "LTF",
    "LTFOODS"
  ]
timeframe: 5m
capital: 60000
leverage: 5
opening_range_mins: 15
volume_filter_multiplier: 2.0
volume_sma_len: 10
take_profit_pct: 1.50
stop_loss_pct: 1.00
square_off: "15:15"
entry_start: "09:30"
entry_end: "10:00"
enable_trailing_sl: false
trailing_trigger_rr: 2.0
trailing_step_rr: 0.5
output_dir: "market_data/orb"
start_date: "2023-03-01"
end_date: "2026-07-06"

# Allocation settings
allocation_strategy: "SINGLE_STOCK" # SINGLE_STOCK or PERCENTAGE_RANKED
allocation_weights: [0.50, 0.30, 0.20] # Weights for rank 1, rank 2, rank 3
priority_ranking: [
    "SBIN",
    "BAJFINANCE",
    "INFY",
    "HDFCBANK",
    "TATAMOTORS"
  ]
