enable_live_stocks: true
symbols: "market_data/orb/choosed_stocks.xlsx" # Excel file containing the stocks to load
timeframe: 5m
capital: 60000
leverage: 5
opening_range_mins: 15
volume_filter_multiplier: 2.0
volume_sma_len: 10
take_profit_pct: 1.50
stop_loss_pct: 1.00
square_off: "15:15"
entry_start: "09:30"
entry_end: "10:30"
enable_trailing_sl: false
trailing_trigger_rr: 2.0
trailing_step_rr: 0.5
max_opening_range_pct: 0.00  # Max opening range width as a percent of price (e.g. 2.0 for 2%). 0.0 to disable.
enable_nifty_filter: true  # Only take trades aligned with Nifty 50 trend (LTP >= Open).
max_breakout_wick_pct: 0.00  # Max breakout candle wick size in breakout direction (e.g. 0.30 for 30%). 0.0 to disable.
output_dir: "market_data/real_orb"
start_date: "2026-04-01"
end_date: "2026-06-30"

# Allocation settings
allocation_strategy: "SINGLE_STOCK" # SINGLE_STOCK or PERCENTAGE_RANKED
allocation_weights: [0.50, 0.30, 0.20] # Weights for rank 1, rank 2, rank 3
priority_ranking: [
    "SBIN",
    "BAJFINANCE",
    "INFY",
    "HDFCBANK",
    "TATAMOTORS"
  ]
